// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo2xR8C_X6aQ8qvpQupAb7h_pzak9OAAM',
    appId: '1:550401556027:web:9e52eebe54e49b1aa5661e',
    messagingSenderId: '550401556027',
    projectId: 'fireflutter-6096b',
    authDomain: 'fireflutter-6096b.firebaseapp.com',
    storageBucket: 'fireflutter-6096b.appspot.com',
    measurementId: 'G-TD2GS8410L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUJjDZMbGwsr08aMEvNzr8quvpB3YO8co',
    appId: '1:550401556027:android:e6e7ea6a69f4898ea5661e',
    messagingSenderId: '550401556027',
    projectId: 'fireflutter-6096b',
    storageBucket: 'fireflutter-6096b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaI689lv4fqSVdjoAzfwE5knzNsQkCLk',
    appId: '1:550401556027:ios:331f424e8ae4076ca5661e',
    messagingSenderId: '550401556027',
    projectId: 'fireflutter-6096b',
    storageBucket: 'fireflutter-6096b.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaI689lv4fqSVdjoAzfwE5knzNsQkCLk',
    appId: '1:550401556027:ios:331f424e8ae4076ca5661e',
    messagingSenderId: '550401556027',
    projectId: 'fireflutter-6096b',
    storageBucket: 'fireflutter-6096b.appspot.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo2xR8C_X6aQ8qvpQupAb7h_pzak9OAAM',
    appId: '1:550401556027:web:c7e63a3b8d5573e4a5661e',
    messagingSenderId: '550401556027',
    projectId: 'fireflutter-6096b',
    authDomain: 'fireflutter-6096b.firebaseapp.com',
    storageBucket: 'fireflutter-6096b.appspot.com',
    measurementId: 'G-2YT8ZHEPR9',
  );
}
